export const dati = [
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '1 way',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '2 way',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '2 pole',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: 'intermediate',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '2 pole',
    Current: 16,
    Terminal: 'Screwless',
  },
  {
    Range: 'Systo',
    Family: 'Switch',
    Sub_Family: 'shutter',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Earth pin',
    Current: 16,
    Terminal: 'Screwless',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Earth resiliant',
    Current: 16,
    Terminal: 'Screwless',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Italian',
    Current: 16,
    Terminal: 'Screwless',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Italian',
    Current: 10,
    Terminal: 'Screwless',
  },
  {
    Range: 'Waterproof',
    Family: 'Switch',
    Sub_Family: '1 way',
    Current: 10,
    Terminal: 'Screw',
  },
  {
    Range: 'Waterproof',
    Family: 'Switch',
    Sub_Family: '2 way',
    Current: 10,
    Terminal: 'Screw',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '2 pole',
    Current: 10,
    Terminal: 'Screw',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: 'intermediate',
    Current: 10,
    Terminal: 'Screw',
  },
  {
    Range: 'Gallery',
    Family: 'Switch',
    Sub_Family: '2 pole',
    Current: 16,
    Terminal: 'Screw',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Earth pin',
    Current: 16,
    Terminal: 'Screw',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Earth resiliant',
    Current: 16,
    Terminal: 'Screw',
  },
  {
    Range: 'Systo',
    Family: 'Socket',
    Sub_Family: 'Italian',
    Current: 16,
    Terminal: 'Screw',
  },
  {
    Range: 'Waterproof',
    Family: 'Switch',
    Sub_Family: 'shutter',
    Current: 10,
    Terminal: 'Screwless',
  },
];
