export default [
  {
    id: 1,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2014',
    exit_date: '01/01/2025',
    country: 'International std',
    product_type: 'Ball presure',
    title: 'IEC 60695-10-2:2014-02 Ed. 3.0',
    folder: 5,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 2,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2015',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'Boxes & Wallboxes',
    title: 'IEC 60670-1:2015-03 Ed. 2',
    folder: 1,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 3,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '03/07/1905',
    exit_date: '01/03/2015',
    country: 'International std',
    product_type: 'Boxes & Wallboxes',
    title: 'IEC 60670-1:2011-07 Ed. 1.1',
    folder: '',
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 4,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '27/06/1905',
    exit_date: '',
    country: 'France',
    product_type: 'Cable trunking system',
    title: 'NF EN 50085-1:2005-11',
    folder: 4,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 5,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '19/06/1905',
    exit_date: '',
    country: 'France',
    product_type: 'Cable-outlet',
    title: 'UTE C 61392:1997-12',
    folder: 4,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 6,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Connessioni per apparecchi illuminazione',
    title: 'CEI EN 61995-1:2008',
    folder: '-',
    language: 'IT',
    format: 'Digital',
    comment: '',
  },
  {
    id: 7,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '29/06/1905',
    exit_date: '01/01/2018',
    country: 'Belgium',
    product_type: 'Dimension box Belgium',
    title: 'NBN C 61-670:2007 Ed. 2',
    folder: 1,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 8,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '24/06/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Dimension box ITALIA',
    title: 'CEI 23-74:2002-09',
    folder: 1,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 9,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '24/06/1905',
    exit_date: '01/01/2027',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 60998-2-2:2002-12 Ed. 2',
    folder: 4,
    language: 'EN',
    format: 'Paper',
    comment: '',
  },
  {
    id: 10,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/07/1905',
    exit_date: '01/01/2019',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 61535:2009/COR1:2014 Ed. 1.1',
    folder: 4,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 11,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '04/07/1905',
    exit_date: '01/01/2019',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 61535:A1:2012-05 Ed. 1.1',
    folder: 4,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 12,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '04/07/1905',
    exit_date: '01/01/2019',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 61535:A1:2012 CSV Ed. 1.1',
    folder: 4,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 13,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/10/2019',
    exit_date: '01/02/2023',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 61535:2019',
    folder: 'NN',
    language: 'NN',
    format: '',
    comment:
      'Prevista nuova edizione Feb 2020 / presente nel nostro database la versione DIN',
  },
  {
    id: 14,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '24/06/1905',
    exit_date: '01/01/2027',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 60998-1:2002-12 Ed. 2',
    folder: 4,
    language: 'EN/FR',
    format: 'Paper',
    comment: '',
  },
  {
    id: 15,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2015',
    exit_date: '01/01/2019',
    country: 'International std',
    product_type: 'Electronic Switch',
    title: 'IEC 60669-2-1:2015-03 CSV Ed. 4.2',
    folder: 4,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 16,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/02/2007',
    exit_date: '01/01/2019',
    country: 'European',
    product_type: 'Electronic Switch',
    title: 'CEI EN 60669-2-2:2007-07 Ed. 2.0',
    folder: 4,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 17,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '30/06/1905',
    exit_date: '',
    country: 'Guide',
    product_type: 'Expression for uncertainty',
    title: 'JCGM 100:2008:2008-09',
    folder: 6,
    language: 'EN',
    format: 'Paper',
    comment: '',
  },
  {
    id: 18,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '05/07/1905',
    exit_date: '01/01/2021',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC 60695-2-10:2013-04 Ed. 2',
    folder: 5,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 19,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '06/07/1905',
    exit_date: '01/01/2021',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC 60695-2-11:2014-02 Ed. 2',
    folder: 5,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 20,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '02/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Guida alle prove ambientali',
    title: 'CEI 104-44:2010',
    folder: '-',
    language: 'IT',
    format: 'Digital',
    comment: '',
  },
  {
    id: 21,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '04/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:2012',
    folder: '-',
    language: 'IT',
    format: 'Digital',
    comment: '',
  },
  {
    id: 22,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '26/06/1905',
    exit_date: '',
    country: 'France',
    product_type: 'IK protection degree',
    title: 'NF EN 62262:2004-04',
    folder: 5,
    language: 'FR',
    format: 'Paper',
    comment: '',
  },
  {
    id: 23,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '24/06/1905',
    exit_date: '01/01/2025',
    country: 'International std',
    product_type: 'Indicator light units',
    title: 'IEC 62094-1:2002-10',
    folder: 4,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 24,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '01/01/2025',
    country: 'International std',
    product_type: 'IP protection degree',
    title: 'IEC 60529:2013-08 Ed. 2.2',
    folder: 5,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 25,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '27/06/1905',
    exit_date: '01/01/2024',
    country: 'France',
    product_type: 'Plugs and sockets 20-32A/400V',
    title: 'NF C 61-315:2005-06',
    folder: 4,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 26,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Prove ambientali',
    title: 'CEI EN 60068-1:2015',
    folder: '-',
    language: 'IT',
    format: 'Digital',
    comment: '',
  },
  {
    id: 27,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '23/05/1905',
    exit_date: '01/01/2005',
    country: 'United Kingdom',
    product_type: 'Scatole mercato inglese',
    title: 'BS 4662:1970',
    folder: '-',
    language: 'EN',
    format: 'Digital',
    comment: '',
  },
  {
    id: 28,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '29/06/1905',
    exit_date: '',
    country: 'Germany',
    product_type: 'Scatole mercato tedesco',
    title: 'VDE DIN 49073:2007',
    folder: '-',
    language: 'DE',
    format: 'Digital',
    comment: '',
  },
  {
    id: 29,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '12/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:1990',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 30,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '15/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A1:1993',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 31,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '21/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A2:1995',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 32,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '23/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A3:1999',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 33,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '23/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A4:2001',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 34,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '26/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A5:2004',
    folder: 3,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 35,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '29/06/1905',
    exit_date: '01/06/2022',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:A6:2007',
    folder: 3,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 36,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '22/06/2017',
    exit_date: '',
    country: 'Belgium',
    product_type: 'Socket-outlet',
    title: 'NBN C 61-112-1:2017',
    folder: 3,
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 37,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '12/10/2011',
    exit_date: '07/03/2017',
    country: 'Denmark',
    product_type: 'Socket-outlet',
    title: 'DS 60884-2-D1:2011-10-12',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 38,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/03/2017',
    exit_date: '',
    country: 'Denmark',
    product_type: 'Socket-outlet',
    title: 'DS 60884-2-D1:2017-03',
    folder: 3,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 39,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2003',
    exit_date: '01/01/2013',
    country: 'France',
    product_type: 'Socket-outlet',
    title: 'NF C 61-314:2003',
    folder: 4,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 40,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/01/2008',
    exit_date: '01/01/2023',
    country: 'France',
    product_type: 'Socket-outlet',
    title: 'NF C 61-314:2008-01',
    folder: 5,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 41,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/05/2010',
    exit_date: '01/01/2023',
    country: 'France',
    product_type: 'Socket-outlet',
    title: 'NF C 61-314:A1:2010-05',
    folder: 6,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 42,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/05/2017',
    exit_date: '',
    country: 'France',
    product_type: 'Socket-outlet',
    title: 'NF C 61-314:2017-05',
    folder: 2,
    language: 'FR',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 43,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/02/2010',
    exit_date: '01/12/2021',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1:2010-02',
    folder: '',
    language: 'DE',
    format: '',
    comment: '',
  },
  {
    id: 44,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/03/2013',
    exit_date: '01/12/2021',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1:2013-03',
    folder: '',
    language: 'DE',
    format: '',
    comment: '',
  },
  {
    id: 45,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2016',
    exit_date: '01/01/2026',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1:2016-01',
    folder: 2,
    language: 'DE',
    format: '',
    comment: '',
  },
  {
    id: 46,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/09/2017',
    exit_date: '01/01/2026',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1:2017-09 Am.1',
    folder: 2,
    language: 'DE',
    format: '',
    comment: '',
  },
  {
    id: 47,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '27/06/1905',
    exit_date: '23/10/2022',
    country: 'Indian',
    product_type: 'Socket-outlet',
    title: 'IS 1293:2005:2005',
    folder: '-',
    language: 'EN',
    format: 'Digital',
    comment: '',
  },
  {
    id: 48,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC 60884-1:2013-02 Ed. 3.2',
    folder: 1,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 49,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC DRAFT 23B/1265-CD (IEC 60884-1):Draft 23B/1265-CD DRAFT',
    folder: 1,
    language: 'EN/FR',
    format: '',
    comment: 'Sostituita da Draft 23B/1285-CD',
  },
  {
    id: 50,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '02/07/1905',
    exit_date: '01/12/2019',
    country: 'Austria',
    product_type: 'Socket-outlet',
    title: 'OVE ÖVE/ÖNORM E 8684-1:2010-03',
    folder: 'NA',
    language: 'DE',
    format: '',
    comment: 'Norma non dispo nel raccoglitore.',
  },
  {
    id: 51,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '19/06/1905',
    exit_date: '11/05/2021',
    country: 'Poland',
    product_type: 'Socket-outlet',
    title: 'PN E 93201:1997',
    folder: 3,
    language: 'PL',
    format: 'Paper',
    comment: '',
  },
  {
    id: 52,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2009',
    exit_date: '01/09/2022',
    country: 'Spain',
    product_type: 'Socket-outlet',
    title: 'UNE 20315-1-1:2009',
    folder: '-',
    language: 'ES',
    format: 'Digital',
    comment: '',
  },
  {
    id: 53,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2009',
    exit_date: '01/09/2022',
    country: 'Spain',
    product_type: 'Socket-outlet',
    title: 'UNE 20315-1-1:2009 +ERRATUM:2011',
    folder: '-',
    language: 'ES',
    format: 'Digital',
    comment: '',
  },
  {
    id: 54,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2009',
    exit_date: '01/09/2022',
    country: 'Spain',
    product_type: 'Socket-outlet',
    title: 'UNE 20315-1-2:2009',
    folder: '-',
    language: 'ES',
    format: 'Digital',
    comment: '',
  },
  {
    id: 55,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '',
    country: 'Sweden',
    product_type: 'Socket-outlet',
    title: 'SS 428 08 34:2013',
    folder: 3,
    language: 'SW/EN',
    format: '',
    comment: '',
  },
  {
    id: 56,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '04/07/1905',
    exit_date: '',
    country: 'Israeli std',
    product_type: 'Socket-outlet',
    title: 'SI 32-1-1:2012',
    folder: 2,
    language: 'EN',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 57,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/08/2009',
    exit_date: '13/02/2021',
    country: 'European',
    product_type: 'Switch',
    title: 'EN 60669-1:2000-05 +A1.2003-06 +A2-2009-08',
    folder: 1,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 58,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/08/2018',
    exit_date: '01/01/2022',
    country: 'European',
    product_type: 'Switch',
    title: 'CEI EN 60669-1:2018-07',
    folder: 1,
    language: 'EN',
    format: '',
    comment: 'Solo differenze dalla versione IEC.',
  },
  {
    id: 59,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '19/06/1905',
    exit_date: '',
    country: 'Indian',
    product_type: 'Switch',
    title: 'IS 3854:1997:1997',
    folder: '-',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 60,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '22/02/2017',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'Switch',
    title: 'IEC 60669-1:2017 Ed. 4',
    folder: 1,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 61,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2009',
    exit_date: '01/01/2020',
    country: 'International std',
    product_type: 'Truking test',
    title: 'IEC 60112:2009-10 Ed. 4.1',
    folder: 5,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 62,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2011',
    exit_date: '',
    country: 'International std',
    product_type: 'USB charger',
    title: 'IEC 62684-1:2011',
    folder: '-',
    language: 'EN',
    format: '',
    comment: 'sostituita da  IEC 62684:2018',
  },
  {
    id: 63,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2005',
    exit_date: '',
    country: 'International std',
    product_type: 'EMC',
    title: 'IEC 61000-4-5:2005-11',
    folder: 5,
    language: 'EN',
    format: '',
    comment: 'sostituita da 2017',
  },
  {
    id: 64,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2005',
    exit_date: '',
    country: 'International std',
    product_type: 'EMC',
    title: 'IEC 61000-6-1:2005-03',
    folder: 5,
    language: 'EN',
    format: '',
    comment: 'sostituita da 2016',
  },
  {
    id: 65,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2008',
    exit_date: '',
    country: 'International std',
    product_type: 'Switch for equipment',
    title: 'IEC 61058-1:2008-04',
    folder: 4,
    language: 'EN',
    format: '',
    comment: 'sostituita da 2016',
  },
  {
    id: 66,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '27/06/1905',
    exit_date: '01/03/2015',
    country: 'European',
    product_type: 'Boxes & Wallboxes',
    title: 'EN 60670-1:2005-10',
    folder: 1,
    language: 'IT',
    format: 'Paper',
    comment: 'Mantenere copia cartacea solo per facilità traduzione',
  },
  {
    id: 67,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '',
    exit_date: '',
    country: 'Guide',
    product_type: 'Expression for uncertainty',
    title: 'ENV 13005:2000-07',
    folder: 6,
    language: 'IT',
    format: 'Paper',
    comment: '',
  },
  {
    id: 68,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/1998',
    exit_date: '',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SEV 1011:1998',
    folder: 3,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 69,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/1995',
    exit_date: '',
    country: 'UK',
    product_type: 'Socket-outlet',
    title: 'BS 1363:1995',
    folder: 3,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 70,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Variante impianti elettrici utilizzatori in BT',
    title: 'CEI 64-8; V2:2015-08',
    folder: '-',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 71,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '08/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione delle infrastrutture per gli impianti di comunicazioni e impianti elettronici negli edifici",
    title: 'CEI:64-50:2016-03',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 72,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2007',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per centri commerciali",
    title: 'CEI:64-51:2007-06',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 73,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '03/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per centri commerciali",
    title: 'CEI 64-51 ;V1:2011-07',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 74,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2006',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti\nausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per edifici scolastici",
    title: 'CEI:64-52:2007-06',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 75,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2011',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti\nausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per edifici scolastici",
    title: 'CEI 64-52 ;V1:2011-07',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 76,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2007',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici.Criteri particolari per locali di pubblico spettacolo",
    title: 'CEI:64-54:2007-06',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 77,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/01/2011',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici.Criteri particolari per locali di pubblico spettacolo",
    title: 'CEI 64-54 ;V1:2011-07',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 78,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2007',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per strutture alberghiere",
    title: 'CEI:64-55:2007-06',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 79,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2011',
    exit_date: '01/11/2019',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per strutture alberghiere",
    title: 'CEI 64-55 ;V1:2011-07',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 80,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '08/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "Impianti adeguati all'utilizzo da parte di persone con disabilità o specifiche necessità",
    title: 'CEI 64-21;2016-12',
    folder: '_',
    language: 'IT',
    format: 'Paper + Digital',
    comment: '',
  },
  {
    id: 81,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '06/07/1905',
    exit_date: '01/01/2024',
    country: 'International std',
    product_type: 'Test IK',
    title: 'IEC 60068-2-75:2014-09 Ed 2.0',
    folder: '-',
    language: 'EN',
    format: 'Digital',
    comment: '',
  },
  {
    id: 82,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'Thermocouples –\nPart 1: EMF specifications and tolerances',
    title: 'IEC  60584-1:2013-08 Ed 3.0',
    folder: '-',
    language: 'EN/FR',
    format: 'Digital',
    comment:
      'applicata per definire tolleranza termocoppia glow wire  IEC 60695-2-10',
  },
  {
    id: 83,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '',
    country: 'Spain',
    product_type: 'Socket-outlet',
    title: 'UNE 20315-1-1:2017',
    folder: '-',
    language: 'ES',
    format: 'Digital',
    comment: '',
  },
  {
    id: 84,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '',
    country: 'Spain',
    product_type: 'Socket-outlet',
    title: 'UNE 20315-1-2:2017',
    folder: '-',
    language: 'ES',
    format: 'Digital',
    comment: '',
  },
  {
    id: 85,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/1987',
    exit_date: '09/01/2004',
    country: 'Nederlands',
    product_type: 'Socket-outlet',
    title: 'NEN 1020:1987',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 86,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '26/06/1905',
    exit_date: '08/01/2019',
    country: 'Nederlands',
    product_type: 'Socket-outlet',
    title: 'NEN 1020:A2:2004',
    folder: 3,
    language: 'NL',
    format: 'Paper',
    comment: '',
  },
  {
    id: 87,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/11/2018',
    exit_date: '08/01/2019',
    country: 'Nederlands',
    product_type: 'Socket-outlet',
    title: 'NEN 1020:2018-02',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 88,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '',
    country: 'France',
    product_type: 'Cable trunking system',
    title: 'NF EN 50085-1:A1:2013 Am.1',
    folder: '',
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 89,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '08/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Connessioni per apparecchi illuminazione',
    title: 'CEI EN 61995-1:A1:2016',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 90,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Belgium',
    product_type: 'Dimension box Belgium',
    title: 'NBN C 61-670:2019 Ed. 3',
    folder: '',
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 91,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V1:2013',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 92,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V2:2015',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 93,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V3:2017',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 94,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V4:2017',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 95,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V4/IS1:2017',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 96,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'guida installazione',
    title: 'CEI 64-8:V5:2019',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 97,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'France',
    product_type: 'Plugs and sockets 20-32A/400V',
    title: 'NF C 61-315:2019-05',
    folder: '',
    language: 'FR',
    format: '',
    comment: '',
  },
  {
    id: 98,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '02/07/1905',
    exit_date: '',
    country: 'Germany',
    product_type: 'Scatole mercato tedesco',
    title: 'VDE DIN 49073 Berichtigung 1:2010',
    folder: '-',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 99,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/01/2009',
    exit_date: '28/02/2022',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SEV 1011:2009',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 100,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '29/06/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Socket-outlet',
    title: 'CEI 23-50:2007-03',
    folder: 2,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 101,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '30/06/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Socket-outlet',
    title: 'CEI 23-50:V1:2008',
    folder: 2,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 102,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '03/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Socket-outlet',
    title: 'CEI 23-50:V2:2011',
    folder: 2,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 103,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Socket-outlet',
    title: 'CEI 23-50:V3:2015',
    folder: 2,
    language: 'IT',
    format: '',
    comment: '',
  },
  {
    id: 104,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type: 'Socket-outlet',
    title: 'CEI 23-50:V4:2015+EC1:2016',
    folder: 2,
    language: 'IT',
    format: 'Digital',
    comment: 'V4 consultabile solo da Ceriani',
  },
  {
    id: 105,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '06/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Switch',
    title: 'IEC Draft 23B_EG18_239C - 60669-1-Ed4-FDIS (1):2014',
    folder: '-',
    language: 'EN',
    format: '',
    comment: 'Sostituita da IEC 60669-1 :2017 Ed. 4',
  },
  {
    id: 106,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC Draft 23B/1248e-CD-60884-1: DRAFT',
    folder: 1,
    language: 'EN/FR',
    format: '',
    comment: 'Sostituita da Draft 23B/1248e-CD',
  },
  {
    id: 107,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC Draft 23B/1249-CD-60884-1: DRAFT',
    folder: 1,
    language: 'EN/FR',
    format: '',
    comment: 'Sostituita da Draft 23B/1265-CD',
  },
  {
    id: 108,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '01/01/2018',
    exit_date: '',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE Draft 542-1-2_2018-0056 DIN VDE 0620-1:2018 DRAFT',
    folder: '',
    language: 'DE',
    format: '',
    comment: 'sostituita da  E DIN VDE 0620-1 (VDE 0620-1):2019-03',
  },
  {
    id: 109,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '01/01/2018',
    exit_date: '',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DRAFT 542-1-2_2018-0057 (DIN VDE 0620-2):2018 DRAFT',
    folder: '',
    language: 'DE',
    format: '',
    comment: 'Prese mobili',
  },
  {
    id: 110,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC DRAFT 89_1463e_CD (IEC 60695-2): DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 111,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE E DIN VDE 0620-1 (VDE 0620-1):2019-03 DRAFT',
    folder: '',
    language: 'DE',
    format: '',
    comment: '',
  },
  {
    id: 112,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC DRAFT 23B/1285-CD: DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 113,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet+usb',
    title: 'IEC DRAFT 23B/1286-CD (IEC 60884-3-1): DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'Superati dalla norma IEC 60884-3-1 :2021',
  },
  {
    id: 114,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/08/2019',
    exit_date: '',
    country: 'Nederlands',
    product_type: 'Socket-outlet',
    title: 'NEN 1020:2019-08',
    folder: 3,
    language: '',
    format: '',
    comment:
      'Substitute the edition 2018-02 draft\nWritten in conjunction IEC 60884-1 +A1:2006 +A2: 2013',
  },
  {
    id: 115,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet+usb',
    title: 'IEC DRAFT 23B_1300e_NP (IEC 60884-3-1):2019 DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'Superati dalla norma IEC 60884-3-1 :2021',
  },
  {
    id: 116,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet+usb',
    title: 'IEC DRAFT 23B_1317e_CD (IEC 60884-3-1):2019 DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'Superati dalla norma IEC 60884-3-1 :2021',
  },
  {
    id: 117,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '',
    exit_date: '',
    country: 'International std',
    product_type: 'Switch',
    title: 'IEC DRAFT 23B_1325_DC:2020-08 DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment:
      'modifiche lievi nel capitolo terminal e IPT come parte integrante della norma',
  },
  {
    id: 118,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/02/2021',
    exit_date: '',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1:2021',
    folder: '',
    language: 'DE',
    format: '',
    comment:
      '2021-06 data valida per il test §10.5 accessibilità alle parti attive con la spina da 1 mm',
  },
  {
    id: 119,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '30/04/2013',
    exit_date: '07/10/2021',
    country: 'International std',
    product_type: 'Xeno test',
    title: 'ISO ISO 4892-2:2013',
    folder: 'Q',
    language: 'EN',
    format: '',
    comment: 'Managed by Quality',
  },
  {
    id: 120,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '16/03/2016',
    exit_date: '',
    country: 'International std',
    product_type: 'QUV Sun exposition rays test',
    title: 'ISO ISO 4892-3:2016',
    folder: 'Q',
    language: 'EN',
    format: '',
    comment: 'Managed by Quality',
  },
  {
    id: 121,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/08/2020',
    exit_date: '',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'DIN EN IEC 61535:2020',
    folder: '',
    language: 'DE',
    format: 'Digital',
    comment: 'Versione DE della norma europea del 2019',
  },
  {
    id: 122,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '12/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC DRAFT 23B/1323e-CDV: DRAFT',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'presentazione rp20lab0019',
  },
  {
    id: 123,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '10/07/1905',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'USB',
    title: 'IEC  62368-1:2018 Ed 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 124,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/07/1905',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC  60083:2015 Ed. 7.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'Compendio degli standard nazionali per prese e spine',
  },
  {
    id: 125,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '08/07/1905',
    exit_date: '',
    country: 'Portugal',
    product_type: 'Socket-outlet',
    title: 'NP 1260-1:2016',
    folder: '',
    language: 'PT',
    format: '',
    comment: 'fogli di normalizzazione su NP 1260-2',
  },
  {
    id: 126,
    parent_id: '',
    type: 'Draft',
    status: 'OBSOLETE',
    entry_date: '12/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC DRAFT 23B/1357/DC:2021',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'sostituita da DRAFT 23B/1368/NP ( 60884-3-2)',
  },
  {
    id: 127,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '10/07/1905',
    exit_date: '',
    country: 'England',
    product_type: 'Plugs',
    title: 'BS 1363-1:2016+A1:2018:2018',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 128,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '09/07/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'USB charger',
    title: 'IEC 61558-1:2017 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: 'General requirements and tests',
  },
  {
    id: 129,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '01/07/1905',
    exit_date: '01/01/2021',
    country: 'International std',
    product_type: 'USB charger',
    title: 'IEC 61558-2-16:2009 Ed. 1.0',
    folder: '',
    language: 'EN',
    format: '',
    comment:
      'Particular requirements and tests for switch mode power supply units\nand transformers for switch mode power supply units',
  },
  {
    id: 130,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '10/07/1905',
    exit_date: '',
    country: 'England',
    product_type: 'Socket-outlet',
    title: 'BS 1363-2:2016+A1:2018:2018',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 131,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Corrosion damage effects of fire affluent',
    title: 'IEC Draft 89/1539/FDIS-IEC 60695-5-1:2021 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 132,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC Draft 89/1536/FDIS-IEC 60695-2-11:2021 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 133,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC Draft 89/1535/FDIS-IEC 60695-2-10:2021 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 134,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC Draft 89/1538/FDIS-IEC 60695-2-13:2021 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 135,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC Draft 86/1537/FDIS-IEC 60695-2-12:2021 Ed. 3.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 136,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '28/06/1905',
    exit_date: '',
    country: 'Poland',
    product_type: 'Socket-outlet',
    title: 'PN IEC 60884-1/AP1/AC1:2006',
    folder: '',
    language: 'PL',
    format: 'Digital',
    comment: '',
  },
  {
    id: 137,
    parent_id: '',
    type: 'Standard',
    status: 'OBSOLETE',
    entry_date: '11/07/1905',
    exit_date: '01/12/2021',
    country: 'Austria',
    product_type: 'Socket-outlet',
    title: 'OVE ÖVE/ÖNORM E 8684-1:2019-12',
    folder: 'NA',
    language: 'DE',
    format: '',
    comment:
      'Norma non dispo nel raccoglitore. da verificare sulla versione successiva',
  },
  {
    id: 138,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '01/01/2025',
    country: 'International std',
    product_type: 'IP protection degree',
    title: 'IEC 60529:1989/AMD2:2013/COR1:2019',
    folder: 5,
    language: 'EN/FR',
    format: '',
    comment: '',
  },
  {
    id: 139,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'Socket-outlet+usb',
    title: 'IEC 60884-3-1:2021 ed.1.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 140,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '04/07/1905',
    exit_date: '',
    country: 'Austria',
    product_type: 'Socket-outlet',
    title: 'OVE ÖVE/ÖNORM E 8622-1:2012-11',
    folder: 'NA',
    language: 'DE',
    format: '',
    comment: 'fogli normativi',
  },
  {
    id: 141,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '04/07/1905',
    exit_date: '',
    country: 'Austria',
    product_type: 'Socket-outlet',
    title: 'OVE ÖVE/ÖNORM E 8626:2012-11',
    folder: 'NA',
    language: 'DE',
    format: '',
    comment: 'calibri',
  },
  {
    id: 142,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'Poland',
    product_type: 'Socket-outlet',
    title: 'PN E 93201:2021',
    folder: 3,
    language: 'PL',
    format: '',
    comment: '',
  },
  {
    id: 143,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet+additional functions',
    title: 'IEC DRAFT 23B/1368/NP ( 60884-3-2):2021',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 144,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet for furniture',
    title: 'IEC DRAFT 23B/1369/NP ( 60884-2-8):2021',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 145,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'Austria',
    product_type: 'Socket-outlet',
    title: 'OVE ÖVE/ÖNORM E 8684-1:2021-12',
    folder: 'NA',
    language: 'DE',
    format: '',
    comment: 'Norma non dispo nel raccoglitore.',
  },
  {
    id: 146,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '25/06/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'Halogen free',
    title: 'IEC 61249-2-21:2003-11 ed.1.0',
    folder: '',
    language: 'EN/FR',
    format: '',
    comment: 'Halogen free for electronics products',
  },
  {
    id: 147,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '12/07/1905',
    exit_date: '01/01/2022',
    country: 'International std',
    product_type: 'Switch',
    title: 'IEC 60669-1/COR1:2020 Ed. 4',
    folder: 1,
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 148,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/08/2013',
    exit_date: '',
    country: 'Germany',
    product_type: 'Fire protection on railway vehicles',
    title: 'DIN 45545-1:2013 Ed. 5',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 149,
    parent_id: '',
    type: 'Draft',
    status: 'In Application',
    entry_date: '14/07/1905',
    exit_date: '',
    country: 'International std',
    product_type: 'Socket-outlet',
    title: 'IEC DRAFT SC23BMT4_0333_INF ( 60884-1):2022 Ed. 4.0',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 150,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '27/06/1905',
    exit_date: '01/01/2027',
    country: 'International std',
    product_type: 'Electrical Connection',
    title: 'IEC 60998-1/ISH1:2005',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 151,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'Electronic Switch',
    title: 'IEC 60669-2-1:2021',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 152,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '01/01/2028',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC 60695-2-10:2021-10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 153,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '01/01/2028',
    country: 'International std',
    product_type: 'Glow wire test',
    title: 'IEC 60695-2-11:2021-10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 154,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '12/07/1905',
    exit_date: '01/01/2023',
    country: 'International std',
    product_type: 'Truking test',
    title: 'IEC 60112:2020',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 155,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '01/01/2025',
    country: 'International std',
    product_type: 'USB charger',
    title: 'IEC 61558-2-16:2021',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 156,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '01/02/2022',
    exit_date: '',
    country: 'Germany',
    product_type: 'Socket-outlet',
    title: 'VDE DIN 0620-1 Berichtigung 1:2022',
    folder: '',
    language: '',
    format: '',
    comment:
      '2021-06 data valida per il test §10.5 accessibilità alle parti attive con la spina da 1 mm',
  },
  {
    id: 157,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'France',
    product_type: 'IK protection degree',
    title: 'NF EN 62262/A1:2021-10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 158,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '13/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "Impianti adeguati all'utilizzo da parte di persone con disabilità o specifiche necessità",
    title: 'CEI 64-21:2021-06',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 159,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per centri commerciali",
    title: 'CEI 64-51;Ab:2007-06',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 160,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti\nausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per edifici scolastici",
    title: 'CEI 64-52 ;Ab:2019-10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 161,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici.Criteri particolari per locali di pubblico spettacolo",
    title: 'CEI 64-54;Ab:2019-10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 162,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Italy',
    product_type:
      "VARIANTE:Guida per l'integrazione degli impianti elettrici utilizzatori e per la predisposizione di impianti ausiliari, telefonici e di trasmissione dati negli edifici. Criteri particolari per strutture alberghiere",
    title: 'CEI 64-55;Ab:2019_10',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 163,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '07/10/2021',
    exit_date: '07/10/2021',
    country: 'International std',
    product_type: 'Xeno test',
    title: 'ISO ISO 4892-2:2021',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 164,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Indian',
    product_type: 'Socket-outlet',
    title: 'IS 1293:2019:2019',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 165,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '',
    country: 'Sweden',
    product_type: 'Socket-outlet',
    title: 'SS 428 08 34 R1:2017',
    folder: '',
    language: '',
    format: '',
    comment:
      'Fixed resistors for use in electronic equipment - Part 8-1: Blank detail specification: Fixed surface mount (SMD) low power film resistors for general electronic equipment, classification level G',
  },
  {
    id: 166,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '05/07/1905',
    exit_date: '',
    country: 'Sweden',
    product_type: 'Socket-outlet',
    title: 'SS 428 08 34 T1:2018',
    folder: '',
    language: '',
    format: '',
    comment: '',
  },
  {
    id: 167,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SN 441011-1+corr :2019',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 168,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SN 441011-2-1+corr :2019',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 169,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SN 441011-2-2+corr :2019',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
  {
    id: 170,
    parent_id: '',
    type: 'Standard',
    status: 'In Application',
    entry_date: '11/07/1905',
    exit_date: '',
    country: 'Swiss',
    product_type: 'Socket-outlet',
    title: 'SN 441011-2-3+corr :2019',
    folder: '',
    language: 'EN',
    format: '',
    comment: '',
  },
];
